spring:
  application:
    name: msclientes

server:
  port: 0 # Porta fica randomica, sobe aleatoria

eureka:
  client:
    service-url:
      defaultZone: http://cursoma-eureka-user:ecok-usr-eeuramssur@localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  charset:
    file: ./logs/log-file.log